server:
  port: 8080
  host: localhost
  shutdown_timeout: 30

deepseek:
  base_url: https://api.deepseek.com
  temperature: 0.7
  timeout: 600

log:
  level: info
  file: logs/agent-forge.log
  enabled: false